version: '3.8'

services:
  demo-app:
    build: .
    image: demo-app:latest
    container_name: demo-springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_H2_CONSOLE_ENABLED: "true"
      SPRING_H2_CONSOLE_PATH: /h2-console
    depends_on:
      - h2db

  h2db:
    image: oscarfonts/h2
    container_name: h2db-container
    ports:
      - "8082:8082"
    environment:
      H2_OPTIONS: -tcp -tcpAllowOthers -tcpPort 9092 -ifNotExists
